// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lwqrjlcyrfchajiorlwl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3cXJqbGN5cmZjaGFqaW9ybHdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3NDMzNzMsImV4cCI6MjA2NzMxOTM3M30.Erz4vlpzokYHgjFB6M3PkZ1JBqVe_7HbWp0JpDdtUWg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});